"""img text

Revision ID: 6db59aac8ef2
Revises: ac2e9d1c68bf
Create Date: 2023-05-09 02:19:55.127634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db59aac8ef2'
down_revision = 'ac2e9d1c68bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
