"""img size largest more

Revision ID: ac2e9d1c68bf
Revises: d58d5f8c83fe
Create Date: 2023-05-09 02:16:41.935860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2e9d1c68bf'
down_revision = 'd58d5f8c83fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
